{
 "title": "Database Performance",
 "tags": [
  "gqlgen-dynamodb",
  "DynamoDB",
  "GraphQL"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "log_source", "query": "loki" },
   { "name": "metrics", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Query Counts",
   "type": "piechart",
   "description": "Number of each type of query requested.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (query_name)(increase(graphql_query_count{}[$__range]))",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "Logs (junk excluded)",
   "type": "logs",
   "gridPos": { "h": 33, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container_name=\"database-gqlgen-dynamodb-1\"} != \"/health\" !=\"/metrics\" !=\"/v1/ping\" !=\"/query\" "
    }
   ]
  },
  {
   "title": "Overall Query Performance",
   "type": "timeseries",
   "description": "95th, 99th, & avg query performance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(graphql_query_request_time_seconds_bucket{}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(graphql_query_request_time_seconds_bucket{}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum(graphql_query_request_time_seconds_sum{}) / sum(graphql_query_request_time_seconds_count{})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Average Query Time",
   "type": "bargauge",
   "description": "Average query times slower than 75ms.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum (graphql_query_request_time_seconds_sum{}) by (query_name) / sum(graphql_query_request_time_seconds_count{}) by (query_name)) ",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "Poor Performing Queries",
   "type": "bargauge",
   "description": "Queries whose 95th percentile duration is longer than 300ms.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(graphql_query_request_time_seconds_bucket{cluster=~\"$cluster\", }[$__rate_interval])) by (le, query_name)) > .10",
     "legendFormat": "{{query_name}}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "increase(graphql_query_failure_count{}[2m])",
     "legendFormat": "{{query_name}}"
    }
   ]
  }
 ]
}