apiVersion: 1

deleteDatasources:
  - name: Cortex

datasources:
- name: Cortex
  type: prometheus
  access: proxy
  orgId: 1
  url: http://cortex:9009/api/prom
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: .*[Tt]raceI[dD]\\":[ ]*\\"(\w{16,32})\\"
        name: trace1
        url: $${__value.raw}
      - datasourceUid: tempo
        matcherRegex: .*[Tt]raceI[dD]="{0,1}(\w{16,32})"{0,1}
        name: trace2
        url: $${__value.raw}
      - datasourceUid: tempo
        matcherRegex: .*[Tt]raceI[dD]":[ ]*"(\w{16,32})"
        name: trace3
        url: $${__value.raw}